/**
 * BizIntel API
 * API documentation for BizIntel
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiAuthLoginPost200Response model module.
 * @module model/ApiAuthLoginPost200Response
 * @version v1.0.0
 */
class ApiAuthLoginPost200Response {
    /**
     * Constructs a new <code>ApiAuthLoginPost200Response</code>.
     * @alias module:model/ApiAuthLoginPost200Response
     */
    constructor() { 
        
        ApiAuthLoginPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiAuthLoginPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiAuthLoginPost200Response} obj Optional instance to populate.
     * @return {module:model/ApiAuthLoginPost200Response} The populated <code>ApiAuthLoginPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiAuthLoginPost200Response();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiAuthLoginPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiAuthLoginPost200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}



/**
 * JWT token for authentication
 * @member {String} token
 */
ApiAuthLoginPost200Response.prototype['token'] = undefined;

/**
 * Logged-in username
 * @member {String} username
 */
ApiAuthLoginPost200Response.prototype['username'] = undefined;






export default ApiAuthLoginPost200Response;

