/**
 * BizIntel API
 * API documentation for BizIntel
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SignUpRequest model module.
 * @module model/SignUpRequest
 * @version v1.0.0
 */
class SignUpRequest {
    /**
     * Constructs a new <code>SignUpRequest</code>.
     * @alias module:model/SignUpRequest
     */
    constructor() { 
        
        SignUpRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SignUpRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignUpRequest} obj Optional instance to populate.
     * @return {module:model/SignUpRequest} The populated <code>SignUpRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignUpRequest();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('inviteCode')) {
                obj['inviteCode'] = ApiClient.convertToType(data['inviteCode'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SignUpRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SignUpRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['inviteCode'] && !(typeof data['inviteCode'] === 'string' || data['inviteCode'] instanceof String)) {
            throw new Error("Expected the field `inviteCode` to be a primitive type in the JSON string but got " + data['inviteCode']);
        }

        return true;
    }


}



/**
 * @member {String} username
 */
SignUpRequest.prototype['username'] = undefined;

/**
 * @member {String} email
 */
SignUpRequest.prototype['email'] = undefined;

/**
 * Password must be at least 8 characters long
 * @member {String} password
 */
SignUpRequest.prototype['password'] = undefined;

/**
 * @member {String} inviteCode
 */
SignUpRequest.prototype['inviteCode'] = undefined;






export default SignUpRequest;

